services:
  mirthconnect:
    image: nextgenhealthcare/connect:4.5.2
    platform: linux/amd64
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE=mysql
      - DATABASE_URL=jdbc:mysql://mysql:3306/mirthdb
      - DATABASE_MAX_CONNECTIONS=20
      - DATABASE_USERNAME=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_MAX_RETRY=2
      - DATABASE_RETRY_WAIT=10000
      - KEYSTORE_STOREPASS=docker_storepass
      - KEYSTORE_KEYPASS=docker_keypass
      - VMOPTIONS=-Xmx512m
      - DELAY=10
    volumes:
      - ${DOCKER_DATA_DIRECTORY}/mirthconnect/appdata:/opt/connect/appdata
      - ${DOCKER_DATA_DIRECTORY}/mirthconnect/logs:/opt/connect/logs
    ports:
      - 8090:8080/tcp
      - 8443:8443/tcp
      - ${MIRTH_INBOUND_PORT}:${MIRTH_INBOUND_PORT}
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.44
    user: "${MYSQL_UID}:${MYSQL_GID}"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=mirthdb
    volumes:
        - ${DOCKER_DATA_DIRECTORY}/mirthconnect/mysql:/var/lib/mysql
    expose:
      - 3306

